package com.sg.qa;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * Represents the complete execution report of one
 * Autonomous QA Agent run.
 *
 * This class contains only execution/reporting data.
 * It does not execute Selenium and does not call Gemini.
 *
 * It tracks:
 *
 * - Generated steps
 * - Executed steps
 * - Passed steps
 * - Failed steps
 * - Blocked steps
 * - Skipped steps
 */
public class ExecutionReport {

    private String website;

    private String overallStatus;

    private LocalDateTime startTime;

    private LocalDateTime endTime;

    /*
     * Number of steps generated by the test-step generator.
     */
    private int generatedSteps;

    /*
     * Number of steps that actually entered execution.
     */
    private int executedSteps;

    /*
     * Number of successfully completed steps.
     */
    private int passedSteps;

    /*
     * Number of failed steps.
     */
    private int failedSteps;

    /*
     * Number of steps that became blocked.
     */
    private int blockedSteps;

    /*
     * Number of downstream steps that were not executed
     * because an earlier step blocked the flow.
     */
    private int skippedSteps;

    private List<StepExecutionResult> stepResults;

    public ExecutionReport() {

        this.stepResults =
                new ArrayList<>();
    }

    public ExecutionReport(
            String website,
            String overallStatus,
            LocalDateTime startTime,
            LocalDateTime endTime,
            int totalSteps,
            int passedSteps,
            int failedSteps,
            int blockedSteps,
            List<StepExecutionResult> stepResults) {

        this.website =
                website;

        this.overallStatus =
                overallStatus;

        this.startTime =
                startTime;

        this.endTime =
                endTime;

        /*
         * Preserve backward compatibility with the
         * existing constructor.
         */
        this.generatedSteps =
                totalSteps;

        this.executedSteps =
                0;

        this.passedSteps =
                passedSteps;

        this.failedSteps =
                failedSteps;

        this.blockedSteps =
                blockedSteps;

        this.skippedSteps =
                0;

        this.stepResults =
                stepResults != null
                        ? new ArrayList<>(stepResults)
                        : new ArrayList<>();

        calculateExecutionSummary();
    }

    public String getWebsite() {

        return website;
    }

    public void setWebsite(
            String website) {

        this.website =
                website;
    }

    public String getOverallStatus() {

        return overallStatus;
    }

    public void setOverallStatus(
            String overallStatus) {

        this.overallStatus =
                overallStatus;
    }

    public LocalDateTime getStartTime() {

        return startTime;
    }

    public void setStartTime(
            LocalDateTime startTime) {

        this.startTime =
                startTime;
    }

    public LocalDateTime getEndTime() {

        return endTime;
    }

    public void setEndTime(
            LocalDateTime endTime) {

        this.endTime =
                endTime;
    }

    /**
     * Backward-compatible total step getter.
     *
     * This represents the number of generated steps.
     */
    public int getTotalSteps() {

        return generatedSteps;
    }

    /**
     * Backward-compatible total step setter.
     */
    public void setTotalSteps(
            int totalSteps) {

        this.generatedSteps =
                totalSteps;
    }

    public int getGeneratedSteps() {

        return generatedSteps;
    }

    public void setGeneratedSteps(
            int generatedSteps) {

        this.generatedSteps =
                generatedSteps;
    }

    public int getExecutedSteps() {

        return executedSteps;
    }

    public void setExecutedSteps(
            int executedSteps) {

        this.executedSteps =
                executedSteps;
    }

    public int getPassedSteps() {

        return passedSteps;
    }

    public void setPassedSteps(
            int passedSteps) {

        this.passedSteps =
                passedSteps;
    }

    public int getFailedSteps() {

        return failedSteps;
    }

    public void setFailedSteps(
            int failedSteps) {

        this.failedSteps =
                failedSteps;
    }

    public int getBlockedSteps() {

        return blockedSteps;
    }

    public void setBlockedSteps(
            int blockedSteps) {

        this.blockedSteps =
                blockedSteps;
    }

    public int getSkippedSteps() {

        return skippedSteps;
    }

    public void setSkippedSteps(
            int skippedSteps) {

        this.skippedSteps =
                skippedSteps;
    }

    public List<StepExecutionResult> getStepResults() {

        return stepResults;
    }

    public void setStepResults(
            List<StepExecutionResult> stepResults) {

        this.stepResults =
                stepResults != null
                        ? new ArrayList<>(stepResults)
                        : new ArrayList<>();
    }

    /**
     * Calculates all execution summary values.
     *
     * Generated steps:
     * Number of steps produced by the test generator.
     *
     * Executed steps:
     * PASS + FAIL + BLOCKED
     *
     * Skipped steps:
     * Steps intentionally not executed because execution
     * was blocked.
     */
    public void calculateSummary() {

        calculateExecutionSummary();
    }

    private void calculateExecutionSummary() {

        if (stepResults == null) {

            stepResults =
                    new ArrayList<>();
        }

        passedSteps = 0;

        failedSteps = 0;

        blockedSteps = 0;

        skippedSteps = 0;

        /*
         * If generatedSteps has not been explicitly set,
         * use the number of recorded results.
         */
        if (generatedSteps <= 0) {

            generatedSteps =
                    stepResults.size();
        }

        for (StepExecutionResult result :
                stepResults) {

            if (result == null) {
                continue;
            }

            String status =
                    result.getStatus();

            if (status == null) {
                continue;
            }

            if ("PASS".equalsIgnoreCase(
                    status)) {

                passedSteps++;

            } else if ("FAIL".equalsIgnoreCase(
                    status)) {

                failedSteps++;

            } else if ("BLOCKED".equalsIgnoreCase(
                    status)) {

                blockedSteps++;

            } else if ("SKIPPED".equalsIgnoreCase(
                    status)) {

                skippedSteps++;
            }
        }

        /*
         * Executed means the step actually attempted execution.
         *
         * SKIPPED steps are intentionally excluded.
         */
        executedSteps =
                passedSteps
                        + failedSteps
                        + blockedSteps;

        /*
         * A skipped step does not itself make the run
         * a failure. The blocking/failed step is what
         * determines the final status.
         */
        if (failedSteps > 0
                || blockedSteps > 0) {

            overallStatus =
                    "FAIL";

        } else {

            overallStatus =
                    "PASS";
        }
    }

    @Override
    public String toString() {

        return "ExecutionReport{" +
                "website='" +
                website + '\'' +
                ", overallStatus='" +
                overallStatus + '\'' +
                ", startTime=" +
                startTime +
                ", endTime=" +
                endTime +
                ", generatedSteps=" +
                generatedSteps +
                ", executedSteps=" +
                executedSteps +
                ", passedSteps=" +
                passedSteps +
                ", failedSteps=" +
                failedSteps +
                ", blockedSteps=" +
                blockedSteps +
                ", skippedSteps=" +
                skippedSteps +
                ", stepResults=" +
                stepResults +
                '}';
    }
}